### ISSUE TITLE
New Permission page is not available

### ISSUE THREAD

**Issue by satrianivzla** [enlivenapp/Open-Blog-3#50]
I was checking this project since you talked about in Facebook and it is pretty cool anyone here is working on it with you?

**Comment by enlivenapp** [comment]
Development-wise, no.  I'm trying to get a stable RC out so people can start using it, but work has been really busy the last few months, so OB has suffered time-wise.

**Comment by satrianivzla** [comment]
I have been working on OB a few weeks and made a lot of changes too ... maybe I can bring you some support with some issues

**Comment by enlivenapp** [comment]
That'd be cool.  I'd also be interested in looking at what you've done with it.

**Comment by enlivenapp** [comment]
I just took an hour or so to download and look over what you've done.

While I can't say I like everything, I do like a lot of what you've done.  The Categories and Language Admin area doesn't look quite like what you have pictured in the readme file, I assume you have updates you haven't pushed yet?

**Comment by satrianivzla** [comment]
Hi enlivenapp, sorry for the late answer.
Yes I have some troubles that moment meanwhile I was updating the folder but I have updated almost everything the blog in the same format as you saw it. 

Also worked in some others things that I would like to add. Let me try to update it and let you know about it

Cheers!

**Comment by satrianivzla** [comment]
Done

I uploaded all files also put in the root folder a SQL file because I was trying to add a track visitors functions and added some additional tables ... I only don't uploaded the install section that I haven't finish to work on it.

Let me know if you are able to run and see the whole changes

Cheers

**Comment by satrianivzla** [comment]
last update that I made  was added sweet alerts to show before delete any record


![untitled-1r](https://cloud.githubusercontent.com/assets/7875387/26655992/317302b8-462b-11e7-8d9c-568f35243666.jpg)

**Comment by enlivenapp** [comment]
Hey,  Sorry for the absence.  I've been extremely busy with normal work.  

I haven't forgotten about you or the work you're doing.  It's going to take some time though before I have much to dedicate to the project.

-M

**Comment by satrianivzla** [comment]
No problem about it I can understand it Be cool and keep working

**Comment by enlivenapp** [comment]
Hey again,

I just downloaded and tried again, I still don't get any popups and there's issues when adding categories (goes to a blank page)

Any further progress?
